### ISSUE TITLE
Failed to import - html-to-react

### ISSUE THREAD

**Issue by majo44** [alephjs/esm.sh#118]
## Failing module

- **GitHub**: https://github.com/aknuds1/html-to-react
- **npm**: https://www.npmjs.com/package/html-to-react

```js
import { Parser } from 'https://esm.sh/html-to-react@1.4.5?dev';
const parser = new Parser();
parser.parse('<div><h1>Title</h1><p>A paragraph</p></div>');
```

## Error message

After running `deno run` I get this:

```
error: Uncaught TypeError: DomHandler is not a constructor
        var handler = new DomHandler();
                      ^
    at parseHtmlToTree (https://cdn.esm.sh/v48/html-to-react@1.4.5/deno/html-to-react.development.js:635:23)
    at parseWithInstructions (https://cdn.esm.sh/v48/html-to-react@1.4.5/deno/html-to-react.development.js:675:23)
    at Object.parse (https://cdn.esm.sh/v48/html-to-react@1.4.5/deno/html-to-react.development.js:684:16)
    at file:///C:/projects/prv/esm-sh-bugs/test.ts:3:8

```

## Additional info

Compiled version of html-to-react contains `
import __domhandler$ from "/v48/domhandler@3.3.0/deno/domhandler.development.js";
`
but `domhandler` has custom *default* export https://github.com/fb55/domhandler/blob/master/src/index.ts#L238 

- **esm.sh version**: v48
- **Deno version**: 1.13.2

**Comment by ije** [comment]
@majo44 thanks, i will look into it 🙏
