### ISSUE TITLE
Option to disable / configure compression

### ISSUE THREAD

**Issue by jimisaacs** [alephjs/esm.sh#121]
So this isn't really an issue with esm.sh, but actually https://github.com/ije/rex which it depends on.
Currently, I can't use brotli in my environment, though to be honest, compression in general is a waste in my environment, i.e. it's just using up CPU. Though because I can't disable it, I'm using a fork and forcing gzip just to make things work.

So what would be the suggestion here? Would you be interested in a PR to https://github.com/ije/rex to allow a server config regarding compression? And a corresponding PR here to use it?

**Comment by ije** [comment]
@jimisaacs i didn't consider this situation, i will move the default competition to a configurable middleware

**Comment by jimisaacs** [comment]
Do you want any help here?

**Comment by ije** [comment]
thanks, just quickly fixed in 9be43ac

**Comment by jimisaacs** [comment]
@ije Nice! I'll give it a quick run

**Comment by jimisaacs** [comment]
@ije 👍 works great! thanks again

**Comment by ije** [comment]
@jimisaacs coola
