### ISSUE TITLE
Failed to import - typescript

### ISSUE THREAD

**Issue by erfanium** [alephjs/esm.sh#131]
## Failing module

- **GitHub**: https://github.com/meilisearch/meilisearch-js
- **npm**: https://www.npmjs.com/package/meilisearch

```
deno run https://esm.sh/meilisearch@0.20.0
```

## Error message

After running `deno run` I get this:

```
error: Import 'https://esm.sh/meilisearch@0.20.0' failed: 408 Request Timeout
```
```
timeout, we are building the package hardly, please try later!
```

## Additional info

It always works well but not today, I think there's a problem with Typescript because it works on browser

- **esm.sh version**: v49 (esm.sh itself)
- **Deno version**: 1.13.2

**Comment by timreichen** [comment]
Same with `http://esm.sh/typescript`

**Comment by ije** [comment]
@erfanium @timreichen  now it should work!
sorry, we are updating the framemwork to run the esm.sh backend on multiple servers, also did some refactors to build the modules more efficiently and better deno types compatibility.

**Comment by timreichen** [comment]
@ije thanks, the previous error is solved, though there is another error that wasn't present before now when trying to import `http://esm.sh/typescript`. Might be related to the updated framework:
```sh
error: Uncaught SyntaxError: The requested module '/v50/events@3.3.0/deno/events.js' does not provide an export named 'EventEmitter'
    at <anonymous> (https://cdn.esm.sh/v50/readable-stream@3.6.0/deno/readable-stream.js:2:116)
```

**Comment by erfanium** [comment]
Thanks, It works now!

**Comment by ije** [comment]
let's keep this open to trace the problem `/v50/events@3.3.0/deno/events.js`

**Comment by ije** [comment]
@timreichen i will fix it ASAP!
