### ISSUE TITLE
Recurred React Invalid Hook Call

### ISSUE THREAD

**Issue by quaos** [alephjs/esm.sh#133]
## Summary

Recently after esm.sh has deprecated the previous bundle mode `import xxx from https://esm.sh/[react,react-dom,...]/react`, I've tried to adjust my Deno projects' deps import/export codes accordingly.

It worked for a while, but then I got previously-encountered `React Invalid Hook Call` error. 

## Error message

After running `yarn build` successfully and then `yarn start`, I get this:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (client.bundle.js:1101)
    at Object.useState2 [as useState] (client.bundle.js:1124)
    at App (client.bundle.js:30151)
    at renderWithHooks (client.bundle.js:15312)
    at mountIndeterminateComponent (client.bundle.js:17493)
    at beginWork (client.bundle.js:18292)
    at HTMLUnknownElement.callCallback2 (client.bundle.js:7577)
    at Object.invokeGuardedCallbackDev (client.bundle.js:7602)
    at invokeGuardedCallback (client.bundle.js:7636)
    at beginWork$1 (client.bundle.js:21478)
```

## Example repository:

https://github.com/quaos/q-portfolio

## Example code:

```js
// src/deps/react.ts
export { default as React } from "https://esm.sh/react@17.0.2?dev&no-check";

// src/deps/react-dom.ts
export { default as ReactDOM } from "https://esm.sh/react-dom@17.0.2?deps=react@17.0.2&dev&no-check";

// src/deps/react-router.ts
export {
  BrowserRouter as Router,
  Link,
  Route,
  Switch,
  useHistory,
  useLocation,
  useParams,
  useRouteMatch,
} from "https://esm.sh/react-router-dom@5.2.1?deps=react@17.0.2&dev&no-check";

```

## Additional info

- **esm.sh version**: v50
- **Deno version**: 1.13.2 (release, x86_64-apple-darwin) (not working on Ubuntu 20.04 server neither)
- ***v8 version***: 9.3.345.11
- ***typescript version***: 4.3.5

**Comment by ije** [comment]
can you please try to clean the cache of deno? i have a plan to remove the traffic feature for china that may case this issues!

**Comment by quaos** [comment]
> can you please try to clean the cache of deno? i have a plan to remove the traffic feature for china that may case this issues!

Thanks! I've cleaned the cache:
`rm -fR  $HOME/Library/Caches/deno/*`

Then run `yarn build` and `yarn start` again. The app now loaded normally.

I suppose you can close the issue.
