### ISSUE TITLE
Failed to import - Deno - JSDOM@17.0.0

### ISSUE THREAD

**Issue by SinaMobasheri** [alephjs/esm.sh#156]
## Failing module

- **GitHub**: **https://github.com/jsdom/jsdom**
- **npm**: **https://www.npmjs.com/package/jsdom**

```js
import jsdom from "https://esm.sh/jsdom@17.0.0";
```

## Error message

After importing module in `deno repl` I get this:

```
Uncaught TypeError: Relative import path "ts4.0/index.d.ts" not prefixed with / or ./ or ../ from "https://cdn.esm.sh/@types/jsdom@16.2.13/index.d.ts"
    at async <anonymous>:2:29
```

## Additional info

- **esm.sh version**: v48
- **Deno version**: 1.13.2

- `import jsdom from "https://cdn.esm.sh/v48/jsdom@17.0.0/deno/jsdom.js";` works fine

**Comment by ije** [comment]
@SinaMobasheri you can disable the tyeps by `?no-check`, i will look into it, thanks

**Comment by talentlessguy** [comment]
seems to work in latest version (incl. types), feel free to reopen if a problem persists

**Comment by jespertheend** [comment]
I'm still having this issue on deno 1.17.
Also the `deno coverage` command doesn't have `--no-check` support (https://github.com/denoland/deno/issues/13161)
