### ISSUE TITLE
Dockerfile CMD env substitution

### ISSUE THREAD

**Issue by guiguan** [alephjs/esm.sh#175]
The latest [dockerfile change](https://github.com/alephjs/esm.sh/blob/master/Dockerfile#L15):

```dockerfile
CMD ["esmd", "--etc-dir", "/esm.sh", "--cache", $CACHE, "--db", $DB, "--fs", $FS "--cdn-domain", $CDN_DOMAIN]
```

Those env vars are not going to be substituted unless [a shell is wrapping them](https://docs.docker.com/engine/reference/builder/#cmd)

**Comment by ije** [comment]
updated, thanks!
