### ISSUE TITLE
Failed to import - fp-ts

### ISSUE THREAD

**Issue by Industrial** [alephjs/esm.sh#185]
## Failing module

- **GitHub**: https://github.com/gcanti/fp-ts
- **npm**: https://npm.im/fp-ts

```js
import * as Eq from 'https://esm.sh/fp-ts/Eq'
```

## Error message

After running `deno run` I get this:

```
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'HKT'.
import { HKT, Kind, Kind2, Kind3, URIS, URIS2, URIS3, URIS4, Kind4 } from './HKT/HKT.d.ts'
         ~~~
    at https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/Contravariant.d.ts:4:10

...

240 more
```

## Additional info
- **esm.sh version**: v53
- **Deno version**:  deno 1.14.1 (release, x86_64-unknown-linux-gnu), v8 9.4.146.15, typescript 4.4.2

Inspecting the problem I found that https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/HKT/HKT.d.ts returns a 404, https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/HKT.d.ts also returns a 404 while https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/Eq.d.ts returns 200.

I am not sure why ESM looks for the path `/HKT/HKT.d.ts` seeing as in the source repo, `HKT.ts` (https://github.com/gcanti/fp-ts/blob/master/src/HKT.ts) is right next to `Eq.ts` (https://github.com/gcanti/fp-ts/blob/master/src/Eq.ts). So I'd expect `/HKT.d.ts` (but that also returns 404).

**Comment by talentlessguy** [comment]
seems to be importing fine on v55
