### ISSUE TITLE
Failed to import - bls-wallet-signer@0.5.1-testDirectBls.3

### ISSUE THREAD

**Issue by voltrevo** [alephjs/esm.sh#193]
## Failing module

- **GitHub**: https://github.com/jzaki/bls-wallet/tree/bw-9-try-direct-hubble-bls
- **npm**: https://www.npmjs.com/package/bls-wallet-signer/v/0.5.1-testDirectBls.3

```ts
import { initBlsWalletSigner } from "https://esm.sh/bls-wallet-signer@0.5.1-testDirectBls.3";
```

## Error message

After running `deno run` I get this:

```
Download https://cdn.esm.sh/v54/bls-wallet-signer@0.5.1-testDirectBls.3/dist/src/index.d.ts
Check file:///home/voltrevo/workspaces/ethf/bls-wallet/aggregator/programs/premerge.ts
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v54/bls-wallet-signer@0.5.1-testDirectBls.3/dist/src/index.d.ts"
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:340:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:111714:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:111980:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:112077:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:113535:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:113336:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:113197:26)
```

## Additional info

- **esm.sh version**: v54
- **Deno version**: 1.14.1

When loading esm.sh/bls-wallet-signer@0.5.1-testDirectBls.3, x-typescript-types points to https://cdn.esm.sh/v54/bls-wallet-signer@0.5.1-testDirectBls.3/dist/src/index.d.ts. That url generates a 500 with message "open /esms/types/v54/bls-wallet-signer@0.5.1-testDirectBls.3/dist/src/index.d.ts: no such file or directory".

## My theory

bls-wallet-signer@0.5.1-testDirectBls.3 depends on @thehubbleproject/bls@0.3.0. That dependency specifies `dist/src/index.d.ts` for its types in package.json, but the file doesn't exist. Now, bls-wallet-signer never imports @thehubbleproject/bls at the top level, so inside nodejs it all works fine, and tsc also gets the type definitions. Nonetheless, I suspect esm.sh is looking at @thehubbleproject/bls's package.json, runs into the missing types file and fails to generate type definitions.

It's probably reasonable for esm.sh to not support this kinda broken set up, but the bug is that types fail to generate in a way that doesn't report where the source of the issue is.

**Comment by talentlessguy** [comment]
now there's a new error:

```
error: Uncaught SyntaxError: The requested module '/v55/@ethersproject/transactions@5.5.0/deno/transactions.js' does not provide an export named 'default'
    at <anonymous> (https://cdn.esm.sh/v55/ethers@5.5.1/deno/lib/utils.js:2:8)
```

**Comment by talentlessguy** [comment]
seems to import fine on v57:

```ts
import { initBlsWalletSigner } from "https://esm.sh/bls-wallet-signer@0.5.1-testDirectBls.3?pin=v57";
```
