### ISSUE TITLE
Failed to import - @aws-sdk/client-kms

### ISSUE THREAD

**Issue by sjmueller** [alephjs/esm.sh#197]
## Failing module

```js
"@aws-sdk/client-kms": "https://esm.sh/@aws-sdk/client-kms"
```

## Error message

After running `deno run` I get this:

```
error: Uncaught SyntaxError: The requested module '/v54/@aws-crypto/sha256-browser@2.0.0/deno/sha256-browser.js' does not provide an export named 'Sha256'
    at <anonymous> (https://cdn.esm.sh/v54/@aws-sdk/client-kms@3.39.0/deno/client-kms.js:2:217728)
```

## Additional info

More context can be found here: https://github.com/aws/aws-sdk-js-v3/issues/2810#issuecomment-955015953:

If you look at the [original source](https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/sha256-browser/src/index.ts#L1):
``` ts
export * from "./crossPlatformSha256";
```
And then in [crossPlatformSha256.ts](https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/sha256-browser/src/crossPlatformSha256.ts#L9):
``` ts
export class Sha256 implements Hash { ... }
```

The intention of this code structure should result in the package exporting the `Sha256` class, but maybe `esbuild` could be misinterpreting, resulting in the output not including `Sha256`.

Note that `https://cdn.skypack.dev/@aws-sdk/client-kms?dts` works as intended, as can be seen here: https://cdn.skypack.dev/-/@aws-crypto/sha256-browser@v2.0.0-hvSgq1UX0ymv6X1i0cjH/dist=es2020,mode=imports/optimized/@aws-crypto/sha256-browser.js

- **esm.sh version**: v54
- **Deno version**: 1.15.3

**Comment by talentlessguy** [comment]
new error on v55:

```
Uncaught TypeError: The requested module '/v55/@aws-crypto/sha256-browser@2.0.0/deno/sha256-browser.js' does not provide an export named 'Sha256'
    at async <anonymous>:2:13
```
