### ISSUE TITLE
Failed to import - https://esm.sh/prismjs@1.25.0

### ISSUE THREAD

**Issue by lucacasonato** [alephjs/esm.sh#201]
## Failing module

- **npm**: prism@1.25.0

```js
import * as Prism from 'https://esm.sh/prismjs@1.25.0'
```

## Error message

408 Request Timeout

The request just hangs forever.

## Additional info

- **esm.sh version**: v56
- **Deno version**: 1.15.3

**Comment by lucacasonato** [comment]
After retrying a couple of times it works, but its not reliable.

**Comment by ije** [comment]
fixed this in v57
