### ISSUE TITLE
Failed to import - jsonschema

### ISSUE THREAD

**Issue by elisee** [alephjs/esm.sh#205]
## Failing module

- **GitHub**: https://github.com/tdegrunt/jsonschema
- **npm**: https://www.npmjs.com/package/jsonschema

```js
import * as jsonschema from "https://esm.sh/jsonschema@1.4.0";
```

## Error message

After running `deno run` I get this:

```
Download https://esm.sh/jsonschema@1.4.0
Download https://cdn.esm.sh/v54/jsonschema@1.4.0/deno/jsonschema.js
Download https://cdn.esm.sh/v54/jsonschema@1.4.0/lib/index.d.ts
Download https://cdn.esm.sh/v54/url@0.11.0/deno/url.js
Download https://cdn.esm.sh/v54/deno_std_node_querystring.js
Download https://cdn.esm.sh/v54/punycode@1.3.2/deno/punycode.js
error: Import 'https://cdn.esm.sh/v54/deno_std_node_querystring.js' failed: 404 Not Found
    at https://cdn.esm.sh/v54/url@0.11.0/deno/url.js:2:28
```

It used to work recently, not sure what happened or when it broke exactly as I only realized it broke when deploying on a new machine.

## Additional info

- **esm.sh version**: v54 (according to the log above)
- **Deno version**: 1.15.3

**Comment by ije** [comment]
try `deno run -r ...`

**Comment by elisee** [comment]
Thanks, it's working now. Seems to now use esm.sh v57.

I had to update my import:

```diff
-import * as jsonschema from "https://esm.sh/jsonschema@1.4.0";
+import jsonschema from "https://esm.sh/jsonschema@1.4.0";
```
