### ISSUE TITLE
Failed to import a module with both pinned version and no check

### ISSUE THREAD

**Issue by Soremwar** [alephjs/esm.sh#207]
## Failing module

```js
import "https://esm.sh/jsonwebtoken@8.5.1?pin=v43&no-check";
```

## Error message
error: Import 'https://esm.sh/jsonwebtoken@8.5.1?pin=v43&no-check=true' failed: 408 Request Timeout

## Additional info

- **esm.sh version**: v43
- **Deno version**: 1.11.5

**Comment by ije** [comment]
<img width="822" alt="Screenshot 2021-11-06 at 13 15 31" src="https://user-images.githubusercontent.com/2883484/140598877-7d3f0a99-3a36-4056-a371-712e6823709b.png">
now it works, same problem to #206
