### ISSUE TITLE
Failed to import -

### ISSUE THREAD

**Issue by fakership** [alephjs/esm.sh#212]
## Failing module
mkdirp
- **GitHub**: 
- **npm**:

```js
[import { something } from 'https://esm.sh/my_module'](https://esm.sh/mkdirp)
```

## Error message

After running `deno run` I get this:

```
import __fs$ from "/error.js?type=unsupported-nodejs-builtin-module&name=fs&importer=mkdirp"
```

## Additional info

- **esm.sh version**: v55
- **Deno version**: 1.15.3
![image](https://user-images.githubusercontent.com/16553183/141250453-41edcc92-e35b-4bce-9a06-61a8148b528f.png)

**Comment by ije** [comment]
nodejs fs module doesn't work in browsers for now
