### ISSUE TITLE
Failed to import for js-sha3, on esm.sh v58

### ISSUE THREAD

**Issue by ebramanti** [alephjs/esm.sh#221]
## Failing module

- **GitHub**: https://github.com/emn178/js-sha3
- **npm**: js-sha3@0.8.0

```js
// working
import { keccak_256 } from "https://esm.sh/js-sha3?pin=v54";

// not working
import { keccak_256 } from "https://esm.sh/js-sha3?pin=v58";
```

## Error message

After running `deno run` I get this:

```
error: Uncaught SyntaxError: The requested module '/v58/js-sha3@0.8.0/deno/js-sha3.development.js' does not provide an export named 'keccak_256'
import { keccak_256 } from "/v58/js-sha3@0.8.0/deno/js-sha3.development.js";
```

## Additional info

- **esm.sh version**: v58
- **Deno version**: 1.15.3

Seems like a similar issue to #200, but seems to have been resolved for that particular package.

**Comment by ebramanti** [comment]
In my use-case, this is a sub-dependency, is there any way I can override the esm.sh version for a nested dependency with the `deps` flag?

**Comment by talentlessguy** [comment]
seems to import on v61:

```
> import sha3 from "https://esm.sh/js-sha3?pin=v61";
undefined
> sha3.keccak_256
[Function] {
  create: [Function],
  update: [Function],
  hex: [Function],
  buffer: [Function],
  arrayBuffer: [Function],
  array: [Function],
  digest: [Function]
}
```
