### ISSUE TITLE
How to set user-agent to require target=node ?

### ISSUE THREAD

**Issue by voxsoftware** [alephjs/esm.sh#242]
Hi, ?target=node was implemented after I report this enhancement: #84 
And is good, but how specify in user-agent target=node ?
I tried setting user-agent to ```Node/14``` but  returned es2021 target.

**Comment by ije** [comment]
since node.js don't support url import, i don't know what `user-agent` is right.

**Comment by voxsoftware** [comment]
My project kwruntime supports URL import: https://github.com/kwruntime/core
esm.sh added support to  my runtime adding node=target: https://github.com/alephjs/esm.sh/issues/84

I know that oficcially node doesn't import URL, but taking consideration you added target=node, I think user-agent can be checked like this: Node/14 Node/16. In other words, if user-agent contains: Node/(version-number) same effect like ?target=node

Please enable.
