### ISSUE TITLE
Failed to import - @testing-library/react and lz-string

### ISSUE THREAD

**Issue by KyleJune** [alephjs/esm.sh#248]
## Failing module

This module is used for testing react components.

- **npm**: https://www.npmjs.com/package/@testing-library/react

```js
export {
  fireEvent,
  render,
  waitFor,
} from "https://esm.sh/@testing-library/react@12.1.2?target=deno&pin=v61";
```

## Error message

After running `deno run --config=deno.json test_deps.ts` I get this:

```
error: Uncaught SyntaxError: The requested module '/v61/lz-string@1.4.4/deno/lz-string.js' does not provide an export named 'compressToEncodedURIComponent'
    at <anonymous> (https://cdn.esm.sh/v61/@testing-library/dom@8.11.1/deno/dom.js:2:670)
```

## Additional info

- **esm.sh version**: v61
- **Deno version**: 1.17.2

I checked https://cdn.esm.sh/v61/lz-string@1.4.4/deno/lz-string.js and compressToEncodedURIComponent appears to be in it.

**Comment by KyleJune** [comment]
It looks like the issue might be that lz-string is exporting default but not exporting the values like it is expected to. I'm able to lz-string by doing the following and lzString has compressToEncodedURIComponent on it.

```
import lzString from "https://esm.sh/lz-string@1.4.4?target=deno&pin=v61";
```

If I import * as lzString, the only key on lzString is default.

**Comment by KyleJune** [comment]
I checked the source for @testing-library/dom, it looks like it expects lz-string to be imported in the way it is being imported in the source code.

https://github.com/testing-library/dom-testing-library/blob/066a41f80e9a6d3c0d248a3ed915c1c52501cf4b/src/screen.ts

Based on that, I think the issue is with lz-string exports being broken on esm.sh

**Comment by ije** [comment]
thanks for the details! i will look into it
