### ISSUE TITLE
Some modules with deno target return 404 on v41

### ISSUE THREAD

**Issue by FallingSnow** [alephjs/esm.sh#74]
I'm not sure why but modules are returning 404 on v41 but not v40...

https://cdn.esm.sh/v41/camel-case@4.1.2/deno/camel-case.development.js
vs
https://cdn.esm.sh/v40/camel-case@4.1.2/deno/camel-case.development.js

**Comment by ije** [comment]
seems it is ok for me

**Comment by FallingSnow** [comment]
Returns
```
{"error":{"status":404,"message":"Not Found"}}
```
for me.

**Comment by ije** [comment]
i believe this has been fixed in https://github.com/postui/esm.sh/commit/453acac1ffdec00a3d269169aba73c5643bdef28
