### ISSUE TITLE
@types/react@17.0.2 type definition build failed

### ISSUE THREAD

**Issue by codehz** [alephjs/esm.sh#82]
https://cdn.esm.sh/v43/@types/react@17.0.2/index.d.ts

and it make many react library stop working with deno lsp

PS:

some library (like [this](https://cdn.esm.sh/v43/framer-motion@4.1.17/types/components/LazyMotion/types.d.ts)) reference https://esm.sh/v43/react@17.0.2/index.d.ts
but it is also wrong:
-> `import * from "https://cdn.esm.sh/v41/react@17.0.2/es2020/index.d.ts.js"`
-> `import{default as d}from"react/index.d.ts";export{d as default};` (invalid relative import)

**Comment by talentlessguy** [comment]
does this still happen with v49?

**Comment by codehz** [comment]
Seems fixed
