### ISSUE TITLE
Please enable target=node 

### ISSUE THREAD

**Issue by voxsoftware** [alephjs/esm.sh#84]
Hi, I made a custom nodejs runtime, [https://github.com/kwruntime/core](https://github.com/kwruntime/core) that works with imports similar to Deno (allowing imports from URLs, typescript out the box, and full ES2020 syntax without .mjs extension), but of course with all nodejs ecosystem.

I see this website, a very cool, but i see your website don't expose feature target=node10, target=node12, etc. that is available in ESBUILD. When target is set to node in ESBUILD, ESBUILD doesn't bundle/convert internal builtin nodejs modules, and is that I want. Please can you enable node target on esm.sh?

**Comment by ije** [comment]
@voxsoftware thanks, great idea! i will implement this ASAP!

**Comment by voxsoftware** [comment]
> @voxsoftware thanks, great idea! i will implement this ASAP!

Thanks. I hope will be available soon. Please let me know.

**Comment by voxsoftware** [comment]
I see now is ?target=node thanks
