### ISSUE TITLE
Support aliasing dependencies

### ISSUE THREAD

**Issue by lucacasonato** [alephjs/esm.sh#89]
For example:

```url
https://esm.sh/swr?alias=react:preact/compat
```

And in combination with `?deps`:

```url
https://esm.sh/swr?alias=react:preact/compat&deps=preact@10.5.14
```

Especially useful for react -> preact :-)

Also, do you accept sponsorship anywhere?

**Comment by ije** [comment]
@lucacasonato thanks, it is a great idea, i will add this feature in few days!  and thanks vary much for the kind sponsorship ask but i can't accept it since github Sponsors doesn't work in my country :(

**Comment by ije** [comment]
@lucacasonato thanks, it is a great idea, i will add this feature in few days!  and thanks vary much for the kind sponsorship ask but i can't accept it since github Sponsors doesn't work in my country :(

**Comment by lucacasonato** [comment]
> can't accept it since github Sponsors doesn't work in my country :( 

Aw, that's very unfortunate. If I can help out in any other way (hosting infrastructure cost for example), please hit me up on Discord. And once Sponsors becomes available on your country, please ping me!

**Comment by shadowtime2000** [comment]
Could be possible expanded to have official deno packages used.

```
https://esm.sh/autoprefixer?alias=postcss:https://deno.land/x/postcss@8.2.0/mod.ts
```

**Comment by ije** [comment]
@lucacasonato @shadowtime2000 **Aliasing** can work now, pls try `https://esm.sh/swr?alias=react:preact/compat`

**Comment by mashaal** [comment]
@ije This looks like it's broken deps in some of my projects.

https://esm.sh/wouter?deps=react@alpha

```
/* esm.sh - wouter@2.7.4 */
export * from "https://cdn.esm.sh/v44/wouter@2.7.4/X-ZGVwczpyZWFjdEAxOC4wLjAtYWxwaGEtYjk5MzRkNmRiLTIwMjEwODA1/es2021/wouter.js";
export { default } from "https://cdn.esm.sh/v44/wouter@2.7.4/X-ZGVwczpyZWFjdEAxOC4wLjAtYWxwaGEtYjk5MzRkNmRiLTIwMjEwODA1/es2021/wouter.js";
```

I might be remembering incorrectly, but I thought deps was passed into the exports in these statements: ie: `v44/wouter?deps=react@alpha`?

**Comment by ije** [comment]
@mashaal alias is different with deps, it is used to replace deps as Luca asked, you can use the `deps` as before that allows you control the dependencies with specific version

**Comment by ije** [comment]
but yes the URL is changed when you passed `?deps`

**Comment by ije** [comment]
i am going to close this since we have implemented this feature in v44, thanks a lot @lucacasonato

**Comment by TomokiMiyauci** [comment]
Can I specify aliases for the dependency of dependency?

Example:

[graphiql](https://github.com/graphql/graphiql/blob/main/packages/graphiql/package.json)
deps:
- @graphiql/react
- react
- react-dom
...and more

[@graphiql/react](https://github.com/graphql/graphiql/blob/main/packages/graphiql-react/package.json)
deps:
- react
- react-dom
...and more

```ts
import GraphiQL from "https://esm.sh/graphiql?alias=react:preact/compat,react-dom:preact/compat";
```

Or you may need the scope of the alias.

```ts
import GraphiQL from "https://esm.sh/graphiql?alias=react:preact/compat,react-dom:preact/compat,@graphiql/react^react:preact/compat";
```
